//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int id_mensaje { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string titulo { get; set; }
        public string mensaje1 { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_ctx { get; set; }
    
        public virtual Contexto Contexto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
